-- Schéma minimal conforme au MCD fourni
CREATE DATABASE IF NOT EXISTS ecole2026 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ecole2026;

-- Admin
CREATE TABLE IF NOT EXISTS Admin (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(150) DEFAULT '',
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  actif TINYINT(1) DEFAULT 1,
  typeAdmin TINYINT DEFAULT 1,
  mobile VARCHAR(50) DEFAULT '',
  alanyaID VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Personne (enseignants, parents, etc.)
CREATE TABLE IF NOT EXISTS Personne (
  idPers INT PRIMARY KEY,
  nom VARCHAR(150) NOT NULL,
  prenom VARCHAR(150) NOT NULL,
  dateNaissance DATE DEFAULT NULL,
  lieuNaissance VARCHAR(200) DEFAULT '',
  mobile VARCHAR(50) DEFAULT '',
  phone VARCHAR(50) DEFAULT '',
  typePersonne TINYINT DEFAULT 1,
  username VARCHAR(150) UNIQUE,
  password VARCHAR(255),
  alanyaID VARCHAR(100) DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Enseignant
CREATE TABLE IF NOT EXISTS Enseignant (
  idEnseignant INT AUTO_INCREMENT PRIMARY KEY,
  idPers INT NOT NULL,
  idCours INT DEFAULT NULL,
  Actif TINYINT(1) DEFAULT 1,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idPers) REFERENCES Personne(idPers) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Eleve
CREATE TABLE IF NOT EXISTS Eleve (
  matricule VARCHAR(50) PRIMARY KEY,
  nom VARCHAR(150) NOT NULL,
  prenom VARCHAR(150) NOT NULL,
  dateNaissance DATE DEFAULT NULL,
  lieuNaissance VARCHAR(200) DEFAULT '',
  sexe TINYINT DEFAULT 1,
  langue VARCHAR(100) DEFAULT 'Francais',
  photoURL VARCHAR(255) DEFAULT '',
  actif TINYINT(1) DEFAULT 1,
  idVilleNaissance INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Cycle
CREATE TABLE IF NOT EXISTS Cycle (
  idCycle INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  description TEXT,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Classe
CREATE TABLE IF NOT EXISTS Classe (
  idClasse INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  idCycle INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idCycle) REFERENCES Cycle(idCycle) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Salle
CREATE TABLE IF NOT EXISTS Salle (
  idSalle INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  position VARCHAR(100) DEFAULT '',
  surface VARCHAR(50) DEFAULT '',
  idClasse INT DEFAULT NULL,
  actif TINYINT(1) DEFAULT 1,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idClasse) REFERENCES Classe(idClasse) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Cours
CREATE TABLE IF NOT EXISTS Cours (
  idCours INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(200) NOT NULL,
  note INT DEFAULT 20,
  coefficient DECIMAL(5,2) DEFAULT 1.0,
  description TEXT,
  idLivre INT DEFAULT NULL,
  actif TINYINT(1) DEFAULT 1,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Livres
CREATE TABLE IF NOT EXISTS Livres (
  idLivre INT AUTO_INCREMENT PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  auteurs VARCHAR(255) DEFAULT '',
  prix DECIMAL(10,2) DEFAULT 0,
  idSpecialite INT DEFAULT NULL,
  edition VARCHAR(100) DEFAULT '',
  annee_parution INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Specialite
CREATE TABLE IF NOT EXISTS Specialite (
  idSpecialite INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  idAdmin INT DEFAULT NULL
) ENGINE=InnoDB;

-- AnneeAcademique
CREATE TABLE IF NOT EXISTS AnneeAcademique (
  idAnnee INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL,
  periode VARCHAR(100) DEFAULT '',
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Trimestre
CREATE TABLE IF NOT EXISTS Trimestre (
  idTrimes INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL,
  periode VARCHAR(100) DEFAULT '',
  idAca INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idAca) REFERENCES AnneeAcademique(idAnnee) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Session
CREATE TABLE IF NOT EXISTS Session (
  idSession INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  description TEXT,
  idTrimestre INT DEFAULT NULL,
  idPers INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idTrimestre) REFERENCES Trimestre(idTrimes) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Frequente (affectation eleve -> salle)
CREATE TABLE IF NOT EXISTS Frequente (
  idFrequente INT AUTO_INCREMENT PRIMARY KEY,
  idSalle INT DEFAULT NULL,
  idAcademi INT DEFAULT NULL,
  matricule VARCHAR(50) DEFAULT NULL,
  commentaire TEXT,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idSalle) REFERENCES Salle(idSalle) ON DELETE SET NULL,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Parents
CREATE TABLE IF NOT EXISTS Parents (
  idParent INT AUTO_INCREMENT PRIMARY KEY,
  idPers INT DEFAULT NULL,
  matricule VARCHAR(50) DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idPers) REFERENCES Personne(idPers) ON DELETE CASCADE,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Rapport
CREATE TABLE IF NOT EXISTS Rapport (
  idRap INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(255) DEFAULT '',
  points INT DEFAULT 0,
  matricule VARCHAR(50) DEFAULT NULL,
  idAca INT DEFAULT NULL,
  commentaire TEXT,
  event_date DATE DEFAULT NULL,
  idPers INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE SET NULL
) ENGINE=InnoDB;

-- EmploiDuTemps
CREATE TABLE IF NOT EXISTS EmploiDuTemps (
  idTemps INT AUTO_INCREMENT PRIMARY KEY,
  jour VARCHAR(30) DEFAULT '',
  heure VARCHAR(20) DEFAULT '',
  idClasse INT DEFAULT NULL,
  idCours INT DEFAULT NULL,
  idSalle INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idClasse) REFERENCES Classe(idClasse) ON DELETE SET NULL,
  FOREIGN KEY (idCours) REFERENCES Cours(idCours) ON DELETE SET NULL,
  FOREIGN KEY (idSalle) REFERENCES Salle(idSalle) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Epreuve, NatureEpreuve, Evaluation
CREATE TABLE IF NOT EXISTS NatureEpreuve (
  idNature INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  description TEXT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Epreuve (
  idEpreuve INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(255) NOT NULL,
  urlDoc VARCHAR(255) DEFAULT '',
  auteur VARCHAR(150) DEFAULT '',
  idNature INT DEFAULT NULL,
  idPers INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idNature) REFERENCES NatureEpreuve(idNature) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Evaluation (
  idEval INT AUTO_INCREMENT PRIMARY KEY,
  note DECIMAL(6,2) DEFAULT 0,
  appreciation TEXT,
  matricule VARCHAR(50) DEFAULT NULL,
  idEpreuve INT DEFAULT NULL,
  idCours INT DEFAULT NULL,
  idSession INT DEFAULT NULL,
  idPers INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE SET NULL,
  FOREIGN KEY (idEpreuve) REFERENCES Epreuve(idEpreuve) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Mode de paiement
CREATE TABLE IF NOT EXISTS Mode (
  idMode INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  information TEXT,
  actif TINYINT(1) DEFAULT 1,
  idFondateur INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Scolarite et Tranches
CREATE TABLE IF NOT EXISTS Scolarite (
  idScolarite INT AUTO_INCREMENT PRIMARY KEY,
  inscription DECIMAL(10,2) DEFAULT 0,
  pension DECIMAL(10,2) DEFAULT 0,
  nbreTranche INT DEFAULT 1,
  description TEXT,
  idCycle INT DEFAULT NULL,
  idFondateur INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Tranches (
  idTranche INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  montant DECIMAL(10,2) DEFAULT 0,
  delai_mois INT DEFAULT 0,
  delai_jour INT DEFAULT 0,
  idScolarite INT DEFAULT NULL,
  actif TINYINT(1) DEFAULT 1,
  idFondateur INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idScolarite) REFERENCES Scolarite(idScolarite) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Messages
CREATE TABLE IF NOT EXISTS Messages (
  idMessages INT AUTO_INCREMENT PRIMARY KEY,
  idExp_Pers INT DEFAULT NULL,
  idParent INT DEFAULT NULL,
  objet VARCHAR(255) DEFAULT '',
  information TEXT,
  type_message VARCHAR(100) DEFAULT '',
  AnneeAcade INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  valider TINYINT(1) DEFAULT 0
) ENGINE=InnoDB;

-- Titulaire
CREATE TABLE IF NOT EXISTS Titulaire (
  idTitulaire INT AUTO_INCREMENT PRIMARY KEY,
  idPers INT DEFAULT NULL,
  idSalle INT DEFAULT NULL,
  actif TINYINT(1) DEFAULT 1,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_personne_username ON Personne(username);
CREATE INDEX IF NOT EXISTS idx_admin_username ON Admin(username);
-- Schéma minimal conforme au MCD fourni
CREATE DATABASE IF NOT EXISTS ecole2026 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE ecole2026;

-- Admin
CREATE TABLE IF NOT EXISTS Admin (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  nom VARCHAR(150) DEFAULT '',
  username VARCHAR(100) UNIQUE NOT NULL,
  password VARCHAR(255) NOT NULL,
  actif TINYINT(1) DEFAULT 1,
  typeAdmin TINYINT DEFAULT 1,
  mobile VARCHAR(50) DEFAULT '',
  alanyaID VARCHAR(100) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Personne (enseignants, parents, etc.)
CREATE TABLE IF NOT EXISTS Personne (
  idPers INT PRIMARY KEY,
  nom VARCHAR(150) NOT NULL,
  prenom VARCHAR(150) NOT NULL,
  dateNaissance DATE DEFAULT NULL,
  lieuNaissance VARCHAR(200) DEFAULT '',
  mobile VARCHAR(50) DEFAULT '',
  phone VARCHAR(50) DEFAULT '',
  typePersonne TINYINT DEFAULT 1,
  username VARCHAR(150) UNIQUE,
  password VARCHAR(255),
  alanyaID VARCHAR(100) DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Enseignant
CREATE TABLE IF NOT EXISTS Enseignant (
  idEnseignant INT AUTO_INCREMENT PRIMARY KEY,
  idPers INT NOT NULL,
  idCours INT DEFAULT NULL,
  Actif TINYINT(1) DEFAULT 1,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idPers) REFERENCES Personne(idPers) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Eleve
CREATE TABLE IF NOT EXISTS Eleve (
  matricule VARCHAR(50) PRIMARY KEY,
  nom VARCHAR(150) NOT NULL,
  prenom VARCHAR(150) NOT NULL,
  dateNaissance DATE DEFAULT NULL,
  lieuNaissance VARCHAR(200) DEFAULT '',
  sexe TINYINT DEFAULT 1,
  langue VARCHAR(100) DEFAULT 'Francais',
  photoURL VARCHAR(255) DEFAULT '',
  actif TINYINT(1) DEFAULT 1,
  idVilleNaissance INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Cycle
CREATE TABLE IF NOT EXISTS Cycle (
  idCycle INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  description TEXT,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Classe
CREATE TABLE IF NOT EXISTS Classe (
  idClasse INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  idCycle INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idCycle) REFERENCES Cycle(idCycle) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Salle
CREATE TABLE IF NOT EXISTS Salle (
  idSalle INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  position VARCHAR(100) DEFAULT '',
  surface VARCHAR(50) DEFAULT '',
  idClasse INT DEFAULT NULL,
  actif TINYINT(1) DEFAULT 1,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idClasse) REFERENCES Classe(idClasse) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Cours
CREATE TABLE IF NOT EXISTS Cours (
  idCours INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(200) NOT NULL,
  note INT DEFAULT 20,
  coefficient DECIMAL(5,2) DEFAULT 1.0,
  description TEXT,
  idLivre INT DEFAULT NULL,
  actif TINYINT(1) DEFAULT 1,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idLivre) REFERENCES Livres(idLivre) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Livres
CREATE TABLE IF NOT EXISTS Livres (
  idLivre INT AUTO_INCREMENT PRIMARY KEY,
  titre VARCHAR(255) NOT NULL,
  auteurs VARCHAR(255) DEFAULT '',
  prix DECIMAL(10,2) DEFAULT 0,
  idSpecialite INT DEFAULT NULL,
  edition VARCHAR(100) DEFAULT '',
  annee_parution INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idSpecialite) REFERENCES Specialite(idSpecialite) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Specialite
CREATE TABLE IF NOT EXISTS Specialite (
  idSpecialite INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  idAdmin INT DEFAULT NULL
) ENGINE=InnoDB;

-- AnneeAcademique
CREATE TABLE IF NOT EXISTS AnneeAcademique (
  idAnnee INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL,
  periode VARCHAR(100) DEFAULT '',
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Trimestre
CREATE TABLE IF NOT EXISTS Trimestre (
  idTrimes INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(100) NOT NULL,
  periode VARCHAR(100) DEFAULT '',
  idAca INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idAca) REFERENCES AnneeAcademique(idAnnee) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Session
CREATE TABLE IF NOT EXISTS Session (
  idSession INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  description TEXT,
  idTrimestre INT DEFAULT NULL,
  idPers INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idTrimestre) REFERENCES Trimestre(idTrimes) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Frequente (affectation eleve -> salle)
CREATE TABLE IF NOT EXISTS Frequente (
  idFrequente INT AUTO_INCREMENT PRIMARY KEY,
  idSalle INT DEFAULT NULL,
  idAcademi INT DEFAULT NULL,
  matricule VARCHAR(50) DEFAULT NULL,
  commentaire TEXT,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idSalle) REFERENCES Salle(idSalle) ON DELETE SET NULL,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Parents
CREATE TABLE IF NOT EXISTS Parents (
  idParent INT AUTO_INCREMENT PRIMARY KEY,
  idPers INT DEFAULT NULL,
  matricule VARCHAR(50) DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idPers) REFERENCES Personne(idPers) ON DELETE CASCADE,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Rapport
CREATE TABLE IF NOT EXISTS Rapport (
  idRap INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(255) DEFAULT '',
  points INT DEFAULT 0,
  matricule VARCHAR(50) DEFAULT NULL,
  idAca INT DEFAULT NULL,
  commentaire TEXT,
  event_date DATE DEFAULT NULL,
  idPers INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE SET NULL
) ENGINE=InnoDB;

-- EmploiDuTemps
CREATE TABLE IF NOT EXISTS EmploiDuTemps (
  idTemps INT AUTO_INCREMENT PRIMARY KEY,
  jour VARCHAR(30) DEFAULT '',
  heure VARCHAR(20) DEFAULT '',
  idClasse INT DEFAULT NULL,
  idCours INT DEFAULT NULL,
  idSalle INT DEFAULT NULL,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idClasse) REFERENCES Classe(idClasse) ON DELETE SET NULL,
  FOREIGN KEY (idCours) REFERENCES Cours(idCours) ON DELETE SET NULL,
  FOREIGN KEY (idSalle) REFERENCES Salle(idSalle) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Epreuve / NatureEpreuve / Evaluation
CREATE TABLE IF NOT EXISTS NatureEpreuve (
  idNature INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  description TEXT
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Epreuve (
  idEpreuve INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(255) NOT NULL,
  urlDoc VARCHAR(255) DEFAULT '',
  auteur VARCHAR(150) DEFAULT '',
  idNature INT DEFAULT NULL,
  idPers INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idNature) REFERENCES NatureEpreuve(idNature) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Evaluation (
  idEval INT AUTO_INCREMENT PRIMARY KEY,
  note DECIMAL(6,2) DEFAULT 0,
  appreciation TEXT,
  matricule VARCHAR(50) DEFAULT NULL,
  idEpreuve INT DEFAULT NULL,
  idCours INT DEFAULT NULL,
  idSession INT DEFAULT NULL,
  idPers INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE SET NULL,
  FOREIGN KEY (idEpreuve) REFERENCES Epreuve(idEpreuve) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Modes de paiement
CREATE TABLE IF NOT EXISTS Mode (
  idMode INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  information TEXT,
  actif TINYINT(1) DEFAULT 1,
  idFondateur INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- Scolarite / Tranches
CREATE TABLE IF NOT EXISTS Scolarite (
  idScolarite INT AUTO_INCREMENT PRIMARY KEY,
  inscription DECIMAL(10,2) DEFAULT 0,
  pension DECIMAL(10,2) DEFAULT 0,
  nbreTranche INT DEFAULT 1,
  description TEXT,
  idCycle INT DEFAULT NULL,
  idFondateur INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS Tranches (
  idTranche INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  montant DECIMAL(10,2) DEFAULT 0,
  delai_mois INT DEFAULT 0,
  delai_jour INT DEFAULT 0,
  idScolarite INT DEFAULT NULL,
  actif TINYINT(1) DEFAULT 1,
  idFondateur INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idScolarite) REFERENCES Scolarite(idScolarite) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Messages
CREATE TABLE IF NOT EXISTS Messages (
  idMessages INT AUTO_INCREMENT PRIMARY KEY,
  idExp_Pers INT DEFAULT NULL,
  idParent INT DEFAULT NULL,
  objet VARCHAR(255) DEFAULT '',
  information TEXT,
  type_message VARCHAR(100) DEFAULT '',
  AnneeAcade INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  valider TINYINT(1) DEFAULT 0
) ENGINE=InnoDB;

-- Titulaire
CREATE TABLE IF NOT EXISTS Titulaire (
  idTitulaire INT AUTO_INCREMENT PRIMARY KEY,
  idPers INT DEFAULT NULL,
  idSalle INT DEFAULT NULL,
  actif TINYINT(1) DEFAULT 1,
  idAdmin INT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB;

-- VilleNaissance
CREATE TABLE IF NOT EXISTS VilleNaissance (
  idVille INT AUTO_INCREMENT PRIMARY KEY,
  libelle VARCHAR(150) NOT NULL,
  actif TINYINT(1) DEFAULT 1
) ENGINE=InnoDB;

-- Indexes
CREATE INDEX idx_personne_username ON Personne(username);
CREATE INDEX idx_admin_username ON Admin(username);
CREATE INDEX idx_eleve_actif ON Eleve(actif);
CREATE INDEX idx_cours_actif ON Cours(actif);
CREATE INDEX idx_enseignant_actif ON Enseignant(Actif);

-- Bulletins
CREATE TABLE IF NOT EXISTS Bulletin (
  idBulletin INT AUTO_INCREMENT PRIMARY KEY,
  matricule VARCHAR(50) DEFAULT NULL,
  idAnnee INT DEFAULT NULL,
  idTrimes INT DEFAULT NULL,
  appreciation TEXT,
  idPers INT DEFAULT NULL,
  statut VARCHAR(50) DEFAULT 'brouillon',
  dateGeneration DATETIME DEFAULT NULL,
  moyenneGenerale DECIMAL(6,2) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (matricule) REFERENCES Eleve(matricule) ON DELETE SET NULL,
  FOREIGN KEY (idAnnee) REFERENCES AnneeAcademique(idAnnee) ON DELETE SET NULL,
  FOREIGN KEY (idTrimes) REFERENCES Trimestre(idTrimes) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS BulletinDetail (
  idDetail INT AUTO_INCREMENT PRIMARY KEY,
  idBulletin INT DEFAULT NULL,
  idCours INT DEFAULT NULL,
  libelleCours VARCHAR(255) DEFAULT '',
  note DECIMAL(6,2) DEFAULT 0,
  appreciation TEXT,
  coefficient DECIMAL(5,2) DEFAULT 1.0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (idBulletin) REFERENCES Bulletin(idBulletin) ON DELETE CASCADE,
  FOREIGN KEY (idCours) REFERENCES Cours(idCours) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE INDEX IF NOT EXISTS idx_bulletin_matricule ON Bulletin(matricule);
